Class {
	#name : 'EnOGDerivationNode',
	#superclass : 'Object',
	#instVars : [
		'declaration',
		'edges'
	],
	#category : 'En-Parsing',
	#package : 'En',
	#tag : 'Parsing'
}

{ #category : 'as yet unclassified' }
EnOGDerivationNode >> instantiate [

	"TODO: should return the obj that represent this object graph derivation"
	1 halt.
]

{ #category : 'as yet unclassified' }
EnOGDerivationNode >> recursiveBackPropagate: improvement from: context seen: set [

	1 halt.
]
